sudo: false
language: python
python:
- '2.7'
addons:
  apt:
    packages:
    - build-essential
    - fp-compiler
    - texlive-latex-base
    - texlive-lang-polish
    - texlive-latex-extra
    - texlive-fonts-recommended
    - libdb-dev
install: pip install codecov tox-travis
script: tox
after_success:
- codecov
