version: '3'
services:
  db:
    image: library/postgres
    restart: always
    environment:
      POSTGRES_USER: "oioioi"
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: "oioioi"
  web:
    command: /sio2/oioioi/oioioi_init.sh
    image: oioioi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: "selenium_settings"
  worker:
    cap_add:
      - ALL
    command: /sio2/oioioi/worker_init.sh
    image: oioioi
    depends_on:
      - db
      - web
    environment:
      DJANGO_SETTINGS_MODULE: "selenium_settings"
  selenium-hub:
    image: selenium/hub
    ports:
      - "4444:4444"
  selenium-firefox:
    image: selenium/node-firefox
    environment:
      HUB_PORT_4444_TCP_ADDR: "hub"
      HUB_PORT_4444_TCP_PORT: "4444"
    links:
      - selenium-hub:hub
      - web:oioioi