version: '3'
services:
  db:
    image: library/postgres
    restart: always
    environment:
      POSTGRES_USER: "oioioi"
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: "oioioi"
  web:
    command: /sio2/oioioi/oioioi_init.sh
    image: oioioi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
  worker:
    cap_add:
      - ALL
    command: /sio2/oioioi/worker_init.sh
    image: oioioi
    depends_on:
      - web
    deploy:
      replicas: 10
