version: '3'
services:
  db:
    image: library/postgres
    restart: always
    environment:
      POSTGRES_USER: "oioioi"
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: "oioioi"
    networks:
      - oioioi_net
  web:
    command: /sio2/oioioi/oioioi_init.sh
    volumes:
      - $PWD:/sio2/oioioi
      - $PWD/logs/:/sio2/oioioi/logs
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - "oioioi_uid=${OIOIOI_UID}"
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - oioioi_net
  worker:
    cap_add:
      - ALL
    command: /sio2/oioioi/worker_init.sh
    volumes:
      - $PWD:/sio2/oioioi
      - $PWD/logs/:/sio2/oioioi/logs
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - "oioioi_uid=${OIOIOI_UID}"
    image: oioioi_dev
    depends_on:
      - db
      - web
    deploy:
      replicas: 1
    networks:
      - oioioi_net

networks:
  oioioi_net:
